apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: middleware-fixed
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@citus-coordinator:5432/historias"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 8000
